apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nb244otcz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nb244otcz-nodejs 
  name: nb244otcz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nb244otcz-nodejs 
